### ISSUE TITLE
Tab opmaak en zichtbaar bug

### ISSUE THREAD

**Issue by arjangeertsema** [synionnl/md-docs-cli#11]
Zie:

- https://documentatie.synion.nl/kbnl/feature/tab-fout/interactieve-shv/index.html#proces
- https://github.com/synionnl/kbnl/blob/feature/tab-fout/docs/interactieve-shv/index.md

1. De proces tabbladen hebben niet allemaal dezelfde hoogte waardoot het grijs niet goed doorloopt.
2. De processen in Chrome niet zichtbaar (versie 95 bug?)
3. In firefox wordt het proces niet meer zichtbaar wanneer je terug navigeert
4. De processen worden in de vervolg tabbladen niet goed geschaald.

**Comment by stiekstra** [comment]
1. De tabs kunnen nu wrappen over meerdere regels en de opmaak van de tabs is hiervoor aangepast.
2. Regels die toegevoegd voor het responsive gedrag van svg's in het algemeen hadden negatieve gevolgen voor de bpmn svg's. Dit is gecorrigeerd.
3. Firefox heeft issues met het berekenen van de svg viewbox voor 'onzichtbare' elementen. Dit is opgelost door de svg opnieuw te te renderen.
4. Het schalen is gerefactored.
