### ISSUE TITLE
Feature bestand html opmaken

### ISSUE THREAD

**Issue by arjangeertsema** [synionnl/md-docs-cli#12]
.feature bestanden worden automatisch vertaald naar een html structuur. Deze graag opmaken.

Zie "acceptance criteria" tabs:

- https://www.synion.nl/feature/bot/blog/bizdevops/living-documentation.html#process
- https://github.com/synionnl/website/blob/feature/bot/docs/blog/bizdevops/living-documentation.md

Zie voor achtergrond informatie: https://docs.specflow.org/projects/specflow-livingdoc/en/latest/LivingDocGenerator/Test-execution-results.html

**Comment by arjangeertsema** [comment]
@stiekstra de uitwerking is bijna goed. Ik zou graag nog zien dat de scenario's in- en uitklapbaar zijn en dat ze beginnen met de ingeklapte status.

**Comment by stiekstra** [comment]
@arjangeertsema Zojuist heb ik de scenario's in- en uitklapbaar gemaakt.

**Comment by arjangeertsema** [comment]
Top, ziet er goed uit!
